"""Recognize what kind of note a file is and cut it into units a model can read whole.

The notes arrive in a handful of shapes, and sending any of them to a model as one blob loses
the structure that makes them interpretable:

  copilot_recap   One file holding many "Company:" sections, each a Microsoft Copilot summary.
                  Each section becomes its own unit, headed by the company it names.
  pcn_template    The President and CEO Network Word/PDF/text template: an attendee table
                  (name and organization) then themes. The attendee table is the only link
                  between a first name in the discussion and a company, so it travels with
                  the unit. Empty template text and ice-breaker themes are removed.
  transcript      VTT/SRT or "Speaker: words" text.
  generic         Anything else, including board minutes.

Units are cut deterministically, in code, so that what reaches the model is small and a
change to one company's section does not invalidate every other section's cached result.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from . import config
from .text import Document

EVENT_RULES = [
    (r"onboarding", "Onboarding Call"),
    (r"\bboard\b", "Board Meeting"),
    (r"president|ceo network|\bpcn\b|cohort", "President and CEO Network Call"),
    (r"ciaic|council", "CIAIC Council Meeting"),
    (r"\bita\b", "ITA Meeting"),
    (r"public policy", "Public Policy Meeting"),
    (r"workshop", "Workshop"),
    (r"focus group", "Focus Group"),
    (r"site visit", "Site Visit"),
    (r"industry exchange", "Industry Exchange"),
    (r"minutes with|interview|one.on.one|1:1", "Partner Conversation"),
    (r"\bnews\b", "News"),
]

RECAP_MARK = re.compile(r"generated by ai\.?\s*be sure to check for accuracy", re.I)
_RECAP_HEADER = re.compile(r"^(?P<name>[^:\n]{2,80}?):\s*$")
_NUMBERED = re.compile(r"^\s*0?(\d)\.\s+([A-Z][A-Za-z &/\-]+?)\s*$")
_SPEAKER_LINE = re.compile(r"^[A-Z][\w.'’-]*(?: [A-Z][\w.'’-]*){0,3}:\s+\S")
# Labels that look like a speaker but are not: "Idea: ...", "Action: ...", "Next steps: ...".
NOT_SPEAKERS = {"idea", "example", "examples", "note", "notes", "action", "actions", "question", "decision",
                "update", "summary", "next steps", "follow-up", "follow up", "topic", "theme", "context",
                "background", "goal", "goals", "outcome", "result", "takeaway", "risk", "issue", "ask"}


@dataclass
class Unit:
    text: str
    label: str = ""
    default_company: str = ""
    attendees: list[tuple[str, str]] = field(default_factory=list)  # (name, affiliation as written)
    hint: str = ""
    part: int = 1
    parts: int = 1
    # The one partner the file's name points to ("Ben Larson - Evonik.txt"), set by the scan
    # from the partner list. Notes often never say the company's name; the file name does.
    file_company: str = ""
    # Contacts named in this text, "Ben Larson (Evonik Industries)", found in code from the
    # uploaded contact list, so the model can tell whose statement is whose.
    known_people: list[str] = field(default_factory=list)


@dataclass
class Shape:
    shape: str
    scope: str  # "partner" or "internal" (Conexus's own governance)
    event_type: str
    series: str
    units: list[Unit]
    text_date_allowed: bool = True
    skipped_reason: str = ""


def event_type_for(path: str, name: str) -> str:
    haystack = f"{path}/{name}".lower().replace("_", " ")
    for pattern, label in EVENT_RULES:
        if re.search(pattern, haystack):
            return label
    return "Other"


def series_for(event_type: str, name: str, text: str) -> str:
    m = re.search(r"cohort\s*(\d+)", f"{name}\n{text[:600]}", re.I)
    if m and event_type == "President and CEO Network Call":
        return f"Cohort {m.group(1)}"
    return event_type


def words(text: str) -> int:
    return len(text.split())


def chunk(text: str, max_words: int = config.MAX_UNIT_WORDS,
          overlap: int = config.CHUNK_OVERLAP_WORDS) -> list[str]:
    """Split on line boundaries into pieces of about max_words, repeating a little context."""
    if words(text) <= max_words + max_words // 6:
        return [text]
    lines = text.split("\n")
    pieces, current, count = [], [], 0
    for line in lines:
        n = words(line)
        if current and count + n > max_words:
            pieces.append("\n".join(current))
            tail, carried = [], 0
            for prev in reversed(current):
                carried += words(prev)
                tail.insert(0, prev)
                if carried >= overlap:
                    break
            current, count = tail, carried
        current.append(line)
        count += n
    if current:
        pieces.append("\n".join(current))
    return pieces


def _units_from(text: str, **common) -> list[Unit]:
    pieces = chunk(text)
    return [Unit(text=p, part=i + 1, parts=len(pieces), **common) for i, p in enumerate(pieces)]


# ---------------------------------------------------------------- copilot recap

def _split_recap(text: str) -> list[tuple[str, bool, str]]:
    """Cut at every Copilot marker (and at top-level headings), headed or not.

    A running onboarding file is not uniform: most sections open "Company:" then the marker,
    some have lost the heading, and later pages are free-form prep notes under Word headings.
    Cutting at each marker keeps every unit small and its cached result independent.
    """
    lines = text.split("\n")
    cuts: list[tuple[int, str, bool]] = []  # (first line, heading text, names a company)
    for i, line in enumerate(lines):
        if RECAP_MARK.search(line):
            j = i - 1
            while j >= 0 and not lines[j].strip():
                j -= 1
            heading = _RECAP_HEADER.match(lines[j].strip()) if j >= 0 else None
            if heading and words(lines[j]) <= 8:
                cuts.append((j, heading.group("name").strip(), True))
            else:
                cuts.append((i, "", False))
        elif re.match(r"^# \S", line):
            cuts.append((i, line[2:].strip(), False))
    if not cuts:
        return [("", False, text)]
    cuts.sort(key=lambda c: c[0])
    sections = []
    if cuts[0][0] > 0 and words("\n".join(lines[:cuts[0][0]])) >= 40:
        sections.append(("", False, "\n".join(lines[:cuts[0][0]]).strip()))
    for n, (start, name, is_company) in enumerate(cuts):
        end = cuts[n + 1][0] if n + 1 < len(cuts) else len(lines)
        body = "\n".join(l for l in lines[start:end] if not RECAP_MARK.search(l))
        if name and body.strip().startswith(name):
            body = body.strip()[len(name):].lstrip(":\n ")
        sections.append((name, is_company, body.strip()))
    return sections


# ---------------------------------------------------------------- PCN template

_TEMPLATE_NOISE = [
    re.compile(r"^theme\s*\d+\s*:\s*(insert|tbd|\.\.\.)?\s*$", re.I),
    re.compile(r"^capture the ", re.I),
    re.compile(r"^key discussion points:?\s*(\|\s*)?(insert)?\s*$", re.I),
    re.compile(r"^#?\s*\|\s*challenge description", re.I),
    re.compile(r"^\d+\s*(\|\s*)*$"),
    re.compile(r"^[\s|☐xXyYnN]*$"),
    re.compile(r"^(confidential|date:?\s*_*)\s*$", re.I),
    re.compile(r"^(insert|add|enter)\b.{0,60}$", re.I),
]
_ICEBREAKER = re.compile(r"ice.?breaker", re.I)


def _is_pcn_template(text: str) -> bool:
    return bool(re.search(r"^\s*0?1\.\s+ATTENDEES", text, re.M | re.I)
                and re.search(r"MAIN THEMES", text, re.I))


def _attendees(text: str) -> list[tuple[str, str]]:
    lines = text.split("\n")
    out, inside = [], False
    for line in lines:
        m = _NUMBERED.match(line)
        if m:
            inside = m.group(2).strip().lower().startswith("attendee")
            continue
        if not inside or "|" not in line:
            continue
        cells = [c.strip() for c in line.split("|")]
        name = cells[0]
        if not name or name.lower() in ("name", "#"):
            continue
        affiliation = cells[1] if len(cells) > 1 else ""
        out.append((name, affiliation))
    return out


def _clean_template(text: str) -> tuple[str, int]:
    """Remove placeholders and ice-breaker themes. Returns (text, words of real content)."""
    kept: list[str] = []
    skipping_theme = False
    in_attendees = False
    substantive = 0
    for line in text.split("\n"):
        stripped = line.strip()
        m = _NUMBERED.match(line)
        if m:
            in_attendees = m.group(2).strip().lower().startswith("attendee")
            skipping_theme = False
            kept.append(line)
            continue
        if re.match(r"^theme\s*\d+\s*:", stripped, re.I):
            skipping_theme = bool(_ICEBREAKER.search(stripped))
        if skipping_theme:
            continue
        if any(p.match(stripped) for p in _TEMPLATE_NOISE):
            continue
        kept.append(line)
        if not in_attendees and not re.match(r"^theme\s*\d+\s*:", stripped, re.I):
            substantive += words(stripped)
    return "\n".join(kept).strip(), substantive


# ---------------------------------------------------------------- entry point

def classify(name: str, path: str, doc: Document) -> Shape:
    text = doc.text
    event_type = event_type_for(path, name)
    scope = "internal" if event_type == "Board Meeting" else "partner"
    series = series_for(event_type, name, text)

    if RECAP_MARK.search(text):
        units = []
        for label, is_company, body in _split_recap(text):
            if words(body) < 15:
                continue
            units.extend(_units_from(
                body, label=label, default_company=label if is_company else "",
                hint="A Microsoft Copilot summary of one onboarding call. The heading names the "
                     "partner company. If there is no heading, name the company from the text, or "
                     "leave it empty. Names inside the text may be misheard."))
        return Shape("copilot_recap", scope, event_type, series, units, text_date_allowed=False,
                     skipped_reason="" if units else "no sections with content")

    if _is_pcn_template(text):
        cleaned, substantive = _clean_template(text)
        if substantive < 25:
            return Shape("pcn_template", scope, event_type, series, [],
                         skipped_reason="template with no discussion filled in")
        attendees = _attendees(cleaned)
        units = _units_from(
            cleaned, attendees=attendees,
            hint="President and CEO Network notes. Lines inside discussion points read "
                 "'Speaker - statement'. The attendee table gives each speaker's organization. "
                 "Ice-breaker themes have already been removed.")
        return Shape("pcn_template", scope, event_type, series, units)

    lines = [l for l in text.split("\n") if l.strip()]
    labels = [l.split(":", 1)[0] for l in lines
              if _SPEAKER_LINE.match(l) and l.split(":", 1)[0].lower() not in NOT_SPEAKERS]
    repeated = {s for s in labels if labels.count(s) >= 3}
    looks_spoken = len(lines) >= 8 and len(labels) / len(lines) >= 0.6 and len(repeated) >= 2
    if doc.kind in ("vtt", "srt") or looks_spoken:
        speakers = doc.speakers or sorted(repeated)
        units = _units_from(
            text, attendees=[(s, "") for s in speakers],
            hint="A transcript. Each line is 'Speaker: words'. Attribute statements to the person "
                 "who made them and to that person's organization.")
        return Shape("transcript", scope, event_type, series, units)

    units = _units_from(text, hint="Meeting notes in no fixed format.")
    return Shape("generic", scope, event_type, series, units,
                 skipped_reason="" if words(text) >= 15 else "almost no text")
